package com.winit.iKonnect.module.form;

import com.winit.iKonnect.dataobject.RadioBTNDO;
import com.winit.iKonnect.dataobject.ServiceDO;
import com.winit.iKonnect.dataobject.ServiceResponseData;
import com.winit.iKonnect.module.base.IBaseView;

import java.util.ArrayList;
import java.util.HashMap;

/**
 * Created by Rahul.Yadav on 5/19/2017.
 */

public interface IFormView extends IBaseView {

    String EMPTY_REASON = "EMPTY_REASON";
    String ENTER_ANSWER = "ENTER_ANSWER";
    String INVAILD_DATE = "INVAILD_DATE";
    String ENTER_PASSPORT = "ENTER_PASSPORT";
    String ENTER_HOSPITAL_NAME = "ENTER_HOSPITAL_NAME";
    String ENTER_HOSPITAL_LOCATION = "ENTER_HOSPITAL_LOCATION";
    String ENTER_GRIEVANCE_AGAINST = "ENTER_GRIEVANCE_AGAINST";
    String ENTER_LOCATION = "ENTER_LOCATION";
    String ENTER_BANK_NAME = "ENTER_BANK_NAME";
    String ENTER_IQUAMA_NAME = "ENTER_IQUAMA_NAME";
    String SELECT_REQUEST_TYPE = "SELECT_REQUEST_TYPE";
    String ENTER_BRANCH = "ENTER_BRANCH";
    String ENTER_ACCOUNT_NO = "ENTER_ACCOUNT_NO";
    String ENTER_BANK_ADDRESS = "ENTER_BANK_ADDRESS";
    String ENTER_IBAN = "ENTER_IBAN";
    String ENTER_SWIFT_CODE = "ENTER_SWIFT_CODE";
    String ENTER_BANK_SORT_CODE = "ENTER_BANK_SORT_CODE";
    String ENTER_VISA_ISSUE = "ENTER_VISA_ISSUE";
    String ENTER_CLINIC_NAME = "ENTER_CLINIC_NAME";
    /*FOR Bank Account Update*/
    String ENTER_BANK_NAME_AS_RECORD = "ENTER_BANK_NAME_AS_RECORD";
    String ENTER_CURRENCY = "ENTER_CURRENCY";
    String SUCCESS = "Success";

    String ENTER_HA_PREVIOUSLY_PAID = "ENTER_HA_PREVIOUSLY_PAID";
    String ENTER_ADVANCE_PAY_MONTH = "ENTER_ADVANCE_PAY_MONTH";
    String ENTER_VALID_PERIOD = "ENTER_VALID_PERIOD";
    String ENTER_FROM_DATE = "ENTER_FROM_DATE";
    String ENTER_TO_DATE = "ENTER_TO_DATE";
    String ENTER_SUBJECT = "ENTER_SUBJECT";
    String ENTER_MESSEGE = "ENTER_MESSEGE";
    String ENTER_NAME = "ENTER_NAME";
    String ENTER_Relationship = "ENTER_Relationship";
    String ENTER_DOB = "ENTER_DOB";
    String ENTER_Nationality = "ENTER_Nationality";
    String ENTER_ID_NUMBER = "ENTER_ID_NUMBER";
    String ADDRESSEDTO = "ADDRESSEDTO";
    String OTHER_INSTRUCTIONS = "OTHER_INSTRUCTIONS";
    String PURPOSE = "PURPOSE";
    String CURRENT_BANK_NAME = "CURRENT_BANK_NAME";
    String CURRENT_IBAN_NO = "CURRENT_IBAN_NO";
    String SALARY_TRANS_TO_SAME_BANK = "SALARY_TRANS_TO_SAME_BANK";
    String BANK_NAME = "BANK_NAME";
    String LOAN_BANK_NAME = "LOAN_BANK_NAME";
    String CC_BANK_NAME = "CC_BANK_NAME";
    String IBAN_NO = "IBAN_NO";
    String HAVE_EXISTING_LOANS = "HAVE_EXISTING_LOANS";
    String HAVE_CREDIT_CARD = "HAVE_CREDIT_CARD";
    String TOTAL_LOAN_TAKEN = "TOTAL_LOAN_TAKEN";
    String LOAN_APPLIED_ON = "LOAN_APPLIED_ON";
    String OUTSTANDING_ASOFDAY = "OUTSTANDING_ASOFDAY";
    String LAST_INSTAL_DUE = "LAST_INSTAL_DUE";
    String MONTHLY_INSTAL = "MONTHLY_INSTAL";
    String PURPOSE_OF_LOAN = "PURPOSE_OF_LOAN";
    String TOTAL_LOAN_AMT_REQ = "TOTAL_LOAN_AMT_REQ";
    String MONTHLY_INSTAL_50 = "MONTHLY_INSTAL_50";
    String MONTHLY_INSTAL_CONDITION = "MONTHLY_INSTAL_CONDITION";
    String OUTSTANDING_AMT = "OUTSTANDING_AMT";
    String CREDIT_LIMIT = "CREDIT_LIMIT";
    String DECLA_CONFIRM = "DECLA_CONFIRM";
    String DECLA_APPROVAL = "DECLA_APPROVAL";
    String DECLA_REQUEST = "DECLA_REQUEST";
    String PURPOSE_OF_RELEASE = "PURPOSE_OF_RELEASE";
    String PURPOSE_OF_RELEASE_OTHERS = "PURPOSE_OF_RELEASE_OTHERS";
    String START_DATE = "START_DATE";
    String END_DATE = "END_DATE";
    String SAP = "SAP";
    String SYSTEM_NETWORK = "SYSTEM_NETWORK";
    String EMAIL = "EMAIL";
    String INTERNET = "INTERNET";
    String TELEPHONE_EXT = "TELEPHONE_EXT";
    String CONTRIBUTION_AMT = "CONTRIBUTION_AMT";
    String NAME_AS_PASSPORT = "NAME_AS_PASSPORT";
    String FATHER_NAME = "FATHER_NAME";
    String MOTHER_NAME = "MOTHER_NAME";
    String NATIONALITY = "NATIONALITY";
    String DATE_OF_BIRTH = "DATE_OF_BIRTH";
    String PLACE_OF_BIRTH = "PLACE_OF_BIRTH";
    String PASSPORT_NO = "PASSPORT_NO";
    String PLACE_OF_ISSUE = "PLACE_OF_ISSUE";
    String DATE_OF_ISSUE = "DATE_OF_ISSUE";
    String DATE_OF_EXPIRY = "DATE_OF_EXPIRY";
    String PROFESSION = "PROFESSION";
    String DATE_OF_LAST_ENTRY = "DATE_OF_LAST_ENTRY";
    String ADDR_ABROAD = "ADDR_ABROAD";
    String R_SHIP_WITH_APPLI = "R_SHIP_WITH_APPLI";
    String REASON_REQUEST = "REASON_REQUEST";
    String ANY_BANK_LOAN = "ANY_BANK_LOAN";
    String ANY_HR_ADVANCE = "ANY_HR_ADVANCE";
    String ANY_TRANS_ADVANCE = "ANY_TRANS_ADVANCE";
    String CREDIT_CARDS = "CREDIT_CARDS";
    String UAE_DRI_LICENSE = "UAE_DRI_LICENSE";
    String TRANSPORT_LOAN = "TRANSPORT_LOAN";
    String TRANSPORT_LOAN_NOT_ELIGIBLE = "TRANSPORT_LOAN_NOT_ELIGIBLE";
    String DRI_LICENSE = "DRI_LICENSE";
    String AMOUNT = "AMOUNT";
    String STAFF_NO = "STAFF_NO";
    String STAFF_NAME = "STAFF_NAME";
    String DEPARTMENT = "DEPARTMENT";
    String DESIGNATION = "DESIGNATION";
    String BRAND_NEW_OR_PRE = "BRAND_NEW_OR_PRE";
    String VEHICLE_MAKE = "VEHICLE_MAKE";
    String VEHICLE_MODEL = "VEHICLE_MODEL";
    String VEHICLE_MODEL_ = "VEHICLE_MODEL_";
    String ODOMETER_READ = "ODOMETER_READ";
    String ODOMETER_READ_ = "ODOMETER_READ_";
    String CHASSIS_NO = "CHASSIS_NO";
    String ENGINE_NO = "ENGINE_NO";
    String ATTACHMENT_TRANSP    = "ATTACHMENT_TRANSP";
    String ATTACHMENT_TRANSP_NEW    = "ATTACHMENT_TRANSP_NEW";
    String NEW_VEHICLE_MAKE = "NEW_VEHICLE_MAKE";
    String NEW_VEHICLE_MODEL = "NEW_VEHICLE_MODEL";
    String NEW_CHASSIS_NO = "NEW_CHASSIS_NO";


    String EMPTY_COMPANY_NAME = "EMPTY_COMPANY_NAME";
    String EMPTY_COMPANY_DETAILS = "EMPTY_COMPANY_DETAILS";
    String EMPTY_BRANCHID = "EMPTY_BRANCHID";
    String EMPTY_AUTHORIZEDPERSON = "AUTHORIZEDPERSON";
    String EMPTY_CONTACTNUMBER = "CONTACTNUMBER";
    String EMPTY_CARDMEMBERFULLNAME = "CARDMEMBERFULLNAME";
    String EMPTY_CARDHOLDER_MOBILE_NUMBER = "CARDHOLDER_MOBILE_NUMBER";
    String EMPTY_EMPLOYEEID = "EMPLOYEEID";
    String EMPTY_SIGNATURE = "EMPTY_SIGNATURE";
    String EMPTY_CARD_STATEMENT_TYPE = "EMPTY_CARD_STATEMENT_TYPE";
    String EMPTY_DATE = "EMPTY_DATE";
    String EMPTY_END_DATE = "EMPTY_END_DATE";
    String EMPTY_CAPTURED_RETAINED_ATM = "EMPTY_CAPTURED_RETAINED_ATM";
    String EMPTY_CARD_STATUS = "EMPTY_CARD_STATUS";
    String EMPTY_CARD_TYPE_STATUS = "EMPTY_CARD_TYPE_STATUS";
    String EMPTY_CHECKBOX = "EMPTY_CHECKBOX";
    String EMPTY_TIME = "EMPTY_TIME";
    String EMPTY_AMOUNT_WITHDRAW = "EMPTY_AMOUNT_WITHDRAW";
    String EMPTY_AMOUNT_RECIVED = "EMPTY_AMOUNT_RECIVED";
    String EMPTY_AMOUNTDISPUTED = "EMPTY_AMOUNTDISPUTED";
    String EMPTY_ATM_LOCATION = "EMPTY_ATM_LOCATION";
    String ENTER_23DIGITS_IBAN = "ENTER_23DIGITS_IBAN";


    String EMPTY_CITY = "EMPTY_CITY";
    String EMPTY_PO_BOX = "EMPTY_PO_BOX";
    String EMPTY_TELNO = "EMPTY_TELNO";
    String EMPTY_FAX = "EMPTY_FAX";
    String EMPTY_MOBILE = "EMPTY_MOBILE";
    String EMPTY_EMAIL = "EMPTY_EMAIL";
    String EMPTY_WEBSITE = "EMPTY_WEBSITE";

    String EMPTY_DESTINATION = "EMPTY_DESTINATION";
    String EMPTY_PURPOSE_OF_TRAVEL = "EMPTY_PURPOSE_OF_TRAVEL";
    String SELECT_TICKETTYPE = "SELECT_TICKETTYPE";
    String EMPTY_VISA = "EMPTY_VISA";
    String HOSTEL_ACCOMIDATION = "HOSTEL_ACCOMIDATION";
    String COST_DEBIT_TO = "COST_DEBIT_TO";
    String EMPTY_SECTOR = "EMPTY_SECTOR";
    String ADVANCEREQUEST = "ADVANCEREQUEST";
    String EMPTY_TYPE_LEAVE = "EMPTY_TYPE_LEAVE";
    String SELEC_SALARY_ADVANCE = "SELEC_SALARY_ADVANCE";
    String DOYOUWANT_LEAVE_SALRY_ADVANCE = "DOYOUWANT_LEAVE_SALRY_ADVANCE";
    String ADVANCE_SALARY = "ADVANCE_SALARY";
    String ATTACHMENT = "ATTACHMENT";
    String NUMBER_LENGHT = "NUMBER_LENGHT";
    String VALID_EMAIL = "VALID_EMAIL";
    String VALID_DATE_SELECTION = "VALID_DATE_SELECTION";


    //newly added
    //Housing Allowance
    String CONFIRMATION_EMPTY = "CONFIRMATION_EMPTY";
    String CONFIRMATION_NOT_EMPTY = "CONFIRMATION_NOT_EMPTY";
    String COMPANY_ACCOMIDATION = "COMPANY_ACCOMIDATION";
    String BANK_LOAN = "BANK_LOAN";
    String OUTSTANDING_HRA = "OUTSTANDING_HRA";
    String ATTACHMENT_EMPTY = "ATTACHMENT_EMPTY";
    String CALL_SALARY_REQUEST = "CALL_SALARY_REQUEST";

    String ZEROVALUE = "ZEROVALUE";
    String RANGEEXCEED = "RANGEEXCEED";
    String EMPTY_EMERGENCY = "EMPTY_EMERGENCY";

    String EMPTY_TOPIC = "EMPTY_TOPIC";
    String EMPTY_SUB_TOPIC = "EMPTY_SUB_TOPIC";
    String WEEKEND = "WEEKEND";


    void showLoder(String msg);

    void hideLoder();

    void setRadioBTN(ArrayList<RadioBTNDO> radioBTNDOs);

    void showAlert(String message, ServiceDO serviceRequestDO);

    void gotFormData(HashMap<String, ServiceResponseData> hmFormDataDetail);
}
